import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import { authHelpers } from '../services/auth.js'
import UpgradeModal, { isLimitMessage } from '../components/UpgradeModal'
import './SignupRegister.css'

function LegalModal({ type, onClose }) {
  const isTerms = type === 'terms'
  return (
    <div onClick={onClose} style={{
      position: 'fixed', inset: 0, zIndex: 9999,
      background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(6px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
    }}>
      <div onClick={e => e.stopPropagation()} style={{
        background: '#0f1120', border: '1px solid rgba(124,107,255,0.3)',
        borderRadius: 18, padding: 32, maxWidth: 640, width: '100%',
        maxHeight: '80vh', overflowY: 'auto', color: '#d1d5db',
        boxShadow: '0 24px 64px rgba(0,0,0,0.6)',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <h2 style={{ margin: 0, color: '#fff', fontSize: 20, fontWeight: 800 }}>
            {isTerms ? 'Terms of Service' : 'Privacy Policy'}
          </h2>
          <button onClick={onClose} style={{
            background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.12)',
            color: '#fff', borderRadius: 8, width: 32, height: 32, cursor: 'pointer', fontSize: 16,
          }}>×</button>
        </div>
        {isTerms ? (
          <div style={{ lineHeight: 1.7, fontSize: 13 }}>
            <p><strong style={{ color: '#a99cff' }}>Last updated: May 2026</strong></p>
            <p>By accessing or using DisruptIQ ("the Platform"), you agree to be bound by these Terms of Service. Please read them carefully.</p>
            <h4 style={{ color: '#fff', marginTop: 20 }}>1. Use of the Platform</h4>
            <p>DisruptIQ is a supply-chain disruption intelligence platform intended for registered business users. You agree to use it only for lawful business purposes and not to misuse, reverse-engineer, or attempt to access systems beyond your authorized scope.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>2. Account Responsibilities</h4>
            <p>You are responsible for maintaining the confidentiality of your credentials. Each account is limited to 50 suppliers on the free tier. You must not share access credentials with unauthorized users.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>3. Data Ownership</h4>
            <p>All supplier data you upload remains your property. DisruptIQ processes it solely to provide the disruption-response service. We do not sell or share your data with third parties.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>4. AI-Generated Outputs</h4>
            <p>Recommendations generated by the AI swarm are advisory in nature. DisruptIQ is not liable for business decisions made based on these outputs. Always exercise independent judgment.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>5. Service Availability</h4>
            <p>We aim for high availability but do not guarantee uninterrupted service. The platform may undergo scheduled maintenance. LLM features depend on third-party API availability.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>6. Termination</h4>
            <p>Either party may terminate the relationship at any time. On deletion, all your data is permanently removed from our systems within 24 hours.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>7. Governing Law</h4>
            <p>These terms are governed by the laws of India. Disputes shall be resolved through binding arbitration in Chennai, Tamil Nadu.</p>
          </div>
        ) : (
          <div style={{ lineHeight: 1.7, fontSize: 13 }}>
            <p><strong style={{ color: '#a99cff' }}>Last updated: May 2026</strong></p>
            <p>DisruptIQ respects your privacy. This policy explains what data we collect, how we use it, and your rights over it.</p>
            <h4 style={{ color: '#fff', marginTop: 20 }}>1. Data We Collect</h4>
            <p>We collect your name, company email, industry, and the supplier data you voluntarily upload. We also log system events (agent actions, event triggers) for audit and performance purposes.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>2. How We Use Your Data</h4>
            <p>Your data is used exclusively to power the disruption-response pipeline — risk scoring, demand forecasting, action recommendations, and memory recall. It is never used for advertising or sold to third parties.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>3. Multi-Tenant Isolation</h4>
            <p>Each client's data is strictly isolated by a unique client ID. No data from one account is ever accessible to another. Seed/demo data is completely separate from your account.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>4. Data Retention</h4>
            <p>Your data is retained as long as your account is active. When you delete your account, all associated data (suppliers, events, memory, audit logs) is permanently deleted within 24 hours.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>5. Security</h4>
            <p>Passwords are hashed using PBKDF2-HMAC-SHA256 with 500,000 iterations. Sessions are tracked with unique JWT IDs and can be revoked instantly. Authentication tokens are stored in httpOnly cookies.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>6. Your Rights</h4>
            <p>You may export all your data at any time from Account Settings → Account Info. You may delete your account and all associated data at any time. Contact support for any data-related requests.</p>
            <h4 style={{ color: '#fff', marginTop: 16 }}>7. Contact</h4>
            <p>For privacy inquiries, raise a support ticket from the platform's "?" button or visit Account Settings → Support.</p>
          </div>
        )}
        <button onClick={onClose} style={{
          marginTop: 24, width: '100%', padding: '12px',
          background: 'linear-gradient(135deg,#7c6bff,#6354e8)',
          color: '#fff', border: 'none', borderRadius: 12,
          fontWeight: 700, fontSize: 14, cursor: 'pointer',
        }}>Close</button>
      </div>
    </div>
  )
}

// Confetti animation effect
function ConfettiCanvas() {
  const canvasRef = React.useRef(null)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    const ctx = canvas.getContext('2d')
    canvas.width = window.innerWidth
    canvas.height = window.innerHeight

    const particles = []

    class Particle {
      constructor() {
        this.x = Math.random() * canvas.width
        this.y = -10
        this.size = Math.random() * 6 + 4
        this.speedX = (Math.random() - 0.5) * 8
        this.speedY = Math.random() * 8 + 6
        this.rotation = Math.random() * 360
        this.rotationSpeed = (Math.random() - 0.5) * 20
        this.color = ['#FFD700', '#FFA500', '#FF69B4', '#87CEEB', '#98FB98', '#FFB6C1'][Math.floor(Math.random() * 6)]
        this.opacity = 1
      }

      update() {
        this.x += this.speedX
        this.y += this.speedY
        this.rotation += this.rotationSpeed
        this.speedY += 0.2
        this.opacity -= 0.015
      }

      draw(ctx) {
        ctx.save()
        ctx.globalAlpha = this.opacity
        ctx.translate(this.x, this.y)
        ctx.rotate((this.rotation * Math.PI) / 180)
        ctx.fillStyle = this.color
        ctx.fillRect(-this.size / 2, -this.size / 2, this.size, this.size)
        ctx.restore()
      }
    }

    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height)

      for (let i = particles.length - 1; i >= 0; i--) {
        particles[i].update()
        particles[i].draw(ctx)
        if (particles[i].opacity <= 0) {
          particles.splice(i, 1)
        }
      }

      if (particles.length > 0) {
        requestAnimationFrame(animate)
      }
    }

    // Create initial burst of confetti
    for (let i = 0; i < 60; i++) {
      particles.push(new Particle())
    }

    animate()

    const handleResize = () => {
      canvas.width = window.innerWidth
      canvas.height = window.innerHeight
    }

    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])

  return <canvas ref={canvasRef} style={{ position: 'fixed', top: 0, left: 0, pointerEvents: 'none', zIndex: 9999 }} />
}

export default function SignupRegister() {
  const navigate = useNavigate()
  const [step, setStep] = useState(1)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [successMessage, setSuccessMessage] = useState(null)
  const [upgradeOpen, setUpgradeOpen] = useState(false)
  const [upgradeMsg, setUpgradeMsg] = useState('')
  const showUpgrade = (msg) => { setUpgradeMsg(msg || ''); setUpgradeOpen(true) }

  // Step 1: Email & Password
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [passwordStrength, setPasswordStrength] = useState(0)

  const [companyName, setCompanyName] = useState('')
  const [industry, setIndustry] = useState('')
  const [contactName, setContactName] = useState('')
  const [headquartersZone, setHeadquartersZone] = useState('')
  const [acceptedTerms, setAcceptedTerms] = useState(false)
  const [legalModal, setLegalModal] = useState(null)

  const [csvContent, setCsvContent] = useState('')
  const [csvWarnings, setCsvWarnings] = useState([])
  const [clientId, setClientId] = useState(null)
  const [token, setToken] = useState(null)

  // Step 3: Excel Upload
  const [uploadMode, setUploadMode] = useState('excel') // 'excel' | 'csv'
  const [xlsxFile, setXlsxFile] = useState(null)
  const [downloadingTemplate, setDownloadingTemplate] = useState(false)

  // Success screen details
  const [registrationTime, setRegistrationTime] = useState(null)
  const [emailSent, setEmailSent] = useState(false)
  const [suppliersImported, setSuppliersImported] = useState(0)
  const [countdown, setCountdown] = useState(4)

  // Show confetti when success screen appears (no auto-redirect)
  React.useEffect(() => {
    if (successMessage === 'onboarding_complete') {
      setCountdown(4)
    }
  }, [successMessage])

  const industries = [
    'Manufacturing',
    'Electronics',
    'Automotive',
    'Pharmaceutical',
    'FMCG',
    'Logistics',
    'Other',
  ]

  // Check password strength
  const checkPasswordStrength = (pwd) => {
    let strength = 0
    if (pwd.length >= 8) strength++
    if (/[a-z]/.test(pwd) && /[A-Z]/.test(pwd)) strength++
    if (/\d/.test(pwd)) strength++
    if (/[!@#$%^&*]/.test(pwd)) strength++
    return strength
  }

  // Step 1: Register
  const handleStep1 = async (e) => {
    e.preventDefault()
    setError(null)

    if (password !== confirmPassword) {
      setError('Passwords do not match')
      return
    }

    if (!companyName.trim() || !industry || !contactName.trim()) {
      setError('Please complete all required account fields')
      return
    }

    if (password.length < 8) {
      setError('Password must be at least 8 characters')
      return
    }

    if (!acceptedTerms) {
      setError('You must accept the Terms and Privacy Policy')
      return
    }

    setLoading(true)
    try {
      const res = await api.signup({
        email,
        password,
        company_name: companyName,
        industry,
        contact_name: contactName,
        headquarters_zone: headquartersZone.trim(),
      })

      setToken(res.token)
      setClientId(res.client_id)
      setRegistrationTime(res.registration_time)
      setEmailSent(!!res.email_sent)
      authHelpers.saveAuth(res.client_id, res.company_name, res.email, res.token)
      setStep(3)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const handleStep2 = async (e) => {
    e.preventDefault()
    setError(null)

    if (!companyName.trim() || !industry) {
      setError('Please fill in all fields')
      return
    }

    setLoading(true)
    try {
      await api.updateCompanyDetails({
        client_id: clientId,
        company_name: companyName,
        industry: industry,
      })
      setStep(3)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  // Step 3: CSV Upload
  const handleCSVUpload = async (e) => {
    e.preventDefault()
    setError(null)
    setCsvWarnings([])

    if (!csvContent.trim()) {
      setError('Please paste CSV or select a file')
      return
    }

    setLoading(true)
    try {
      const res = await api.importSuppliers({
        csv_content: csvContent,
      })

      setCsvWarnings(res.warnings || [])
      setSuppliersImported(res.supplier_count || 0)
      if (res.limit_reached) showUpgrade((res.warnings || []).find(isLimitMessage))
      setSuccessMessage('onboarding_complete')
    } catch (err) {
      if (isLimitMessage(err.message)) showUpgrade(err.message)
      else setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const handleCSVFileUpload = (e) => {
    const file = e.target.files?.[0]
    if (!file) return

    const reader = new FileReader()
    reader.onload = (event) => {
      setCsvContent(event.target?.result || '')
    }
    reader.readAsText(file)
  }

  // Download the Excel supplier template
  const handleDownloadTemplate = async () => {
    setDownloadingTemplate(true)
    setError(null)
    try {
      const blob = await api.downloadSupplierTemplate()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'disruptiq_supplier_template.xlsx'
      a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      setError('Failed to download template: ' + err.message)
    } finally {
      setDownloadingTemplate(false)
    }
  }

  // Step 3 (Excel): Upload the filled Excel file
  const handleExcelUpload = async (e) => {
    e.preventDefault()
    setError(null)
    setCsvWarnings([])

    if (!xlsxFile) {
      setError('Please select an Excel file (.xlsx) to upload')
      return
    }

    setLoading(true)
    try {
      const res = await api.uploadSupplierExcel(xlsxFile)
      setCsvWarnings(res.errors || [])
      setSuppliersImported(res.suppliers_added || 0)
      setEmailSent(res.email_sent || false)
      if (res.limit_reached) showUpgrade(res.message)
      setSuccessMessage('onboarding_complete')
    } catch (err) {
      if (isLimitMessage(err.message)) showUpgrade(err.message)
      else setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const csvExample = `supplier_name,location,category
Supplier Alpha,Chennai,Electronics
Supplier Beta,Mumbai,Logistics
Supplier Gamma,Bengaluru,Components
Supplier Delta,Pune,Machinery
`

  if (successMessage === 'onboarding_complete') {
    const detailCards = [
      { label: 'Company',         value: companyName,             icon: '🏢', mono: false },
      { label: 'Email',           value: email,                   icon: '✉️', mono: false, small: true },
      { label: 'Account ID',      value: clientId,                icon: '🔑', mono: true },
      { label: 'Suppliers Added', value: String(suppliersImported), icon: '🏭', mono: false },
    ]
    const steps = [
      { icon: '📊', title: 'Dashboard',    desc: 'Supplier data, disruption analysis & real-time alerts' },
      { icon: '🗺️', title: 'Twin Map',     desc: 'Visualize your network with a live digital twin' },
      { icon: '📋', title: 'Reports',      desc: 'Detailed analytics & performance metrics' },
      { icon: '⚙️', title: 'Configuration', desc: 'Set monitoring thresholds & manage suppliers' },
      { icon: '⚡', title: 'Trigger Events', desc: 'Test the system with sample disruption scenarios' },
    ]
    return (
      <>
      <UpgradeModal open={upgradeOpen} message={upgradeMsg} onClose={() => setUpgradeOpen(false)} />
      <div style={{
        minHeight: '100vh', width: '100%', display: 'flex',
        alignItems: 'center', justifyContent: 'center', padding: '32px 16px',
        background:
          'radial-gradient(ellipse 70% 50% at 30% 0%, rgba(124,107,255,0.16) 0%, transparent 60%),' +
          'radial-gradient(ellipse 60% 50% at 80% 100%, rgba(45,212,191,0.12) 0%, transparent 60%),' +
          '#060918',
        position: 'relative', overflow: 'hidden',
      }}>
        <ConfettiCanvas />

        <div style={{
          width: '100%', maxWidth: 640, position: 'relative', zIndex: 2,
          borderRadius: 24, padding: '40px 36px',
          background: 'linear-gradient(160deg, rgba(16,22,46,0.96) 0%, rgba(8,11,28,0.98) 100%)',
          border: '1px solid rgba(124,107,255,0.28)',
          boxShadow: '0 30px 80px rgba(0,0,0,0.6), 0 0 0 1px rgba(124,107,255,0.08), inset 0 1px 0 rgba(255,255,255,0.05)',
          animation: 'su-rise 0.6s cubic-bezier(0.22,1,0.36,1) both',
        }}>
          {/* Animated shimmer top line */}
          <div style={{
            position: 'absolute', top: 0, left: 24, right: 24, height: 2, borderRadius: 2,
            background: 'linear-gradient(90deg,transparent,#7c6bff 35%,#2dd4bf 65%,transparent)',
            backgroundSize: '200% 100%', animation: 'su-shimmer 3.5s linear infinite',
          }} />

          {/* Header */}
          <div style={{ textAlign: 'center', marginBottom: 28 }}>
            <div style={{
              width: 88, height: 88, margin: '0 auto 18px', borderRadius: '50%',
              display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 42,
              background: 'radial-gradient(circle at 30% 30%, rgba(124,107,255,0.35), rgba(45,212,191,0.12))',
              border: '1px solid rgba(124,107,255,0.4)',
              boxShadow: '0 0 40px rgba(124,107,255,0.45)',
              animation: 'su-float 3s ease-in-out infinite',
            }}>🚀</div>
            <h1 style={{
              margin: '0 0 10px', fontSize: 38, fontWeight: 900, letterSpacing: '-0.03em',
              background: 'linear-gradient(90deg,#fff 0%,#c4b8ff 45%,#2dd4bf 100%)',
              backgroundSize: '200% 100%', WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent', animation: 'su-shimmer 5s linear infinite',
            }}>Congratulations!</h1>
            <p style={{ margin: 0, fontSize: 16, color: 'rgba(255,255,255,0.55)', fontWeight: 500 }}>
              Your supply chain intelligence platform is <span style={{ color: '#2dd4bf', fontWeight: 700 }}>live</span>
            </p>
          </div>

          {/* Account detail cards */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 18 }}>
            {detailCards.map((c, i) => (
              <div key={c.label} style={{
                padding: '14px 16px', borderRadius: 14,
                background: 'rgba(255,255,255,0.035)', border: '1px solid rgba(255,255,255,0.08)',
                animation: `su-rise 0.5s ${0.15 + i * 0.08}s cubic-bezier(0.22,1,0.36,1) both`,
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 7 }}>
                  <span style={{ fontSize: 13 }}>{c.icon}</span>
                  <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase' }}>{c.label}</span>
                </div>
                <div style={{
                  fontSize: c.small ? 13 : c.mono ? 12.5 : 17, fontWeight: c.mono ? 600 : 800,
                  color: c.mono ? '#2dd4bf' : '#fff', wordBreak: 'break-all',
                  fontFamily: c.mono ? 'monospace' : 'inherit', lineHeight: 1.35,
                }}>{c.value}</div>
              </div>
            ))}
          </div>

          {/* Email status */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24,
            padding: '13px 16px', borderRadius: 14,
            background: emailSent ? 'rgba(45,212,191,0.08)' : 'rgba(245,158,11,0.08)',
            border: `1px solid ${emailSent ? 'rgba(45,212,191,0.32)' : 'rgba(245,158,11,0.32)'}`,
          }}>
            <span style={{ fontSize: 22 }}>{emailSent ? '✅' : '📧'}</span>
            <div>
              <div style={{ fontSize: 13.5, fontWeight: 700, color: emailSent ? '#2dd4bf' : '#fbbf24' }}>
                {emailSent ? 'Confirmation Email Sent' : 'Confirmation email being sent…'}
              </div>
              <div style={{ fontSize: 11.5, color: 'rgba(255,255,255,0.45)', marginTop: 2 }}>
                {emailSent ? 'Check your email for setup instructions' : "You'll receive it shortly"}
              </div>
            </div>
          </div>

          {/* Getting started */}
          <div style={{
            padding: '18px 18px 14px', borderRadius: 16, marginBottom: 24,
            background: 'rgba(124,107,255,0.06)', border: '1px solid rgba(124,107,255,0.18)',
          }}>
            <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '0.12em', color: '#a99cff', textTransform: 'uppercase', marginBottom: 14 }}>
              ⚡ Getting Started
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {steps.map((s) => (
                <div key={s.title} style={{ display: 'flex', gap: 11, alignItems: 'flex-start' }}>
                  <div style={{
                    width: 30, height: 30, borderRadius: 9, flexShrink: 0, fontSize: 14,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: 'rgba(124,107,255,0.14)', border: '1px solid rgba(124,107,255,0.25)',
                  }}>{s.icon}</div>
                  <div style={{ lineHeight: 1.4 }}>
                    <span style={{ fontSize: 13, fontWeight: 700, color: '#e8e8ff' }}>{s.title}: </span>
                    <span style={{ fontSize: 12.5, color: 'rgba(255,255,255,0.55)' }}>{s.desc}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <button
            onClick={() => navigate(`/dashboard/${clientId}`)}
            style={{
              width: '100%', padding: '15px', borderRadius: 13, border: 'none', cursor: 'pointer',
              background: 'linear-gradient(135deg,#7c6bff,#2dd4bf)', color: '#fff',
              fontSize: 15.5, fontWeight: 800, letterSpacing: '0.01em',
              boxShadow: '0 0 26px rgba(124,107,255,0.5), inset 0 1px 0 rgba(255,255,255,0.2)',
              transition: 'transform 0.18s, box-shadow 0.18s', marginBottom: 12,
            }}
            onMouseEnter={(e) => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 8px 34px rgba(124,107,255,0.65)' }}
            onMouseLeave={(e) => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 0 26px rgba(124,107,255,0.5), inset 0 1px 0 rgba(255,255,255,0.2)' }}
          >
            Enter Your Dashboard →
          </button>
          <button
            onClick={() => navigate('/demo')}
            style={{
              width: '100%', padding: '13px', borderRadius: 13, cursor: 'pointer',
              background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(124,107,255,0.3)',
              color: 'rgba(255,255,255,0.8)', fontSize: 13.5, fontWeight: 700, transition: 'all 0.18s',
            }}
            onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(124,107,255,0.12)'; e.currentTarget.style.borderColor = 'rgba(124,107,255,0.55)' }}
            onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.04)'; e.currentTarget.style.borderColor = 'rgba(124,107,255,0.3)' }}
          >
            Explore Demo Features First
          </button>

          <p style={{ margin: '18px 0 0', textAlign: 'center', fontSize: 11.5, color: 'rgba(255,255,255,0.32)' }}>
            Need help? Contact <span style={{ color: '#a99cff' }}>kcsbadp@gmail.com</span>
          </p>
        </div>

        <style>{`
          @keyframes su-rise { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
          @keyframes su-float { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-9px); } }
          @keyframes su-shimmer { 0% { background-position: -200% 0; } 100% { background-position: 200% 0; } }
        `}</style>
      </div>
      </>
    )
  }

  return (
    <>
    {legalModal && <LegalModal type={legalModal} onClose={() => setLegalModal(null)} />}
    <UpgradeModal open={upgradeOpen} message={upgradeMsg} onClose={() => setUpgradeOpen(false)} />
    <div className="signup-container">
      <div className="signup-card">
        <div className="signup-header">
          <h1>Get Started with DisruptIQ</h1>
          <div className="step-indicator">
            <div className={`step ${step >= 1 ? 'active' : ''}`}>1</div>
            <div className={`step ${step >= 2 ? 'active' : ''}`}>2</div>
            <div className={`step ${step >= 3 ? 'active' : ''}`}>3</div>
          </div>
        </div>

        {error && <div className="error-message">{error}</div>}

        {/* Step 1: Email & Password */}
        {step === 1 && (
          <form onSubmit={handleStep1} className="signup-form">
            <h2>Create Your Account</h2>

            <div className="form-group">
              <label>Company Name</label>
              <input
                type="text"
                value={companyName}
                onChange={(e) => setCompanyName(e.target.value)}
                placeholder="Acme Manufacturing Inc."
                required
              />
            </div>

            <div className="form-group">
              <label>Industry</label>
              <select value={industry} onChange={(e) => setIndustry(e.target.value)} required>
                <option value="">Select an industry...</option>
                {industries.map((ind) => (
                  <option key={ind} value={ind}>
                    {ind}
                  </option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label>Contact Name</label>
              <input
                type="text"
                value={contactName}
                onChange={(e) => setContactName(e.target.value)}
                placeholder="Your name"
                required
              />
            </div>

            <div className="form-group">
              <label>Headquarters / Factory City <span style={{color:'#a78bfa',fontWeight:400,fontSize:12}}>(optional — anchors your Twin Map)</span></label>
              <input
                type="text"
                list="hq-zone-list"
                value={headquartersZone}
                onChange={(e) => setHeadquartersZone(e.target.value)}
                placeholder="e.g. Mumbai, Chennai, Frankfurt — we'll auto-correct typos"
              />
              <datalist id="hq-zone-list">
                {['Mumbai','Chennai','Delhi','Bengaluru','Kolkata','Pune','Hyderabad','Ahmedabad','Jaipur','Kochi','Coimbatore','Lucknow','Shanghai','Shenzhen','Tokyo','Seoul','Singapore','Bangkok','Frankfurt','Rotterdam','London','Dubai','Houston','Los Angeles','New York','Chicago','São Paulo','Mexico City','Sydney','Melbourne'].map(z => (
                  <option key={z} value={z} />
                ))}
              </datalist>
              <div style={{fontSize:11,color:'#94a3b8',marginTop:4,lineHeight:1.4}}>
                Where do your suppliers ship to? We render this as the centre of your supply network. Spelt wrong? We'll fuzzy-match it (e.g. "Mumabi" → Mumbai).
              </div>
            </div>

            <div className="form-group">
              <label>Email Address</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value.toLowerCase())}
                placeholder="your@company.com"
                required
              />
            </div>

            <div className="form-group">
              <label>Password</label>
              <input
                type="password"
                value={password}
                onChange={(e) => {
                  setPassword(e.target.value)
                  setPasswordStrength(checkPasswordStrength(e.target.value))
                }}
                placeholder="Min 8 characters"
                required
              />
              {password && (
                <div className="password-strength">
                  <div className={`strength-bar level-${passwordStrength}`}></div>
                  <span className="strength-text">
                    {passwordStrength === 0 && 'Weak'}
                    {passwordStrength === 1 && 'Fair'}
                    {passwordStrength === 2 && 'Good'}
                    {passwordStrength === 3 && 'Strong'}
                    {passwordStrength === 4 && 'Very Strong'}
                  </span>
                </div>
              )}
            </div>

            <div className="form-group">
              <label>Confirm Password</label>
              <input
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                placeholder="Re-enter password"
                required
              />
            </div>

            <label style={{ display: 'flex', gap: 10, alignItems: 'center', justifyContent: 'flex-start', fontSize: 13, color: 'var(--text-sec)', marginBottom: 16, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={acceptedTerms}
                onChange={(e) => setAcceptedTerms(e.target.checked)}
                required
                style={{ width: 18, height: 18, flexShrink: 0, margin: 0, accentColor: '#7c6bff', cursor: 'pointer' }}
              />
              <span style={{ lineHeight: 1.4 }}>I accept the{' '}
                <button type="button" onClick={() => setLegalModal('terms')} style={{ background: 'none', border: 'none', padding: 0, color: '#a99cff', fontWeight: 700, cursor: 'pointer', textDecoration: 'underline', fontSize: 'inherit' }}>Terms</button>
                {' '}and{' '}
                <button type="button" onClick={() => setLegalModal('privacy')} style={{ background: 'none', border: 'none', padding: 0, color: '#a99cff', fontWeight: 700, cursor: 'pointer', textDecoration: 'underline', fontSize: 'inherit' }}>Privacy Policy</button>.
              </span>
            </label>

            <button type="submit" className="btn btn-primary btn-lg" disabled={loading}>
              {loading ? 'Creating Account...' : 'Next: Import Suppliers'}
            </button>

            <p className="already-have">
              Already have an account? <a href="/login">Sign In</a>
            </p>
          </form>
        )}

        {/* Step 2: Company Details */}
        {step === 2 && (
          <form onSubmit={handleStep2} className="signup-form">
            <h2>Tell Us About Your Company</h2>

            <div className="form-group">
              <label>Company Name</label>
              <input
                type="text"
                value={companyName}
                onChange={(e) => setCompanyName(e.target.value)}
                placeholder="Acme Manufacturing Inc."
                required
              />
            </div>

            <div className="form-group">
              <label>Industry</label>
              <select value={industry} onChange={(e) => setIndustry(e.target.value)} required>
                <option value="">Select an industry...</option>
                {industries.map((ind) => (
                  <option key={ind} value={ind}>
                    {ind}
                  </option>
                ))}
              </select>
            </div>

            <div className="form-actions">
              <button type="button" className="btn btn-secondary" onClick={() => setStep(1)} disabled={loading}>
                Back
              </button>
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Saving Details...' : 'Next: Import Suppliers'}
              </button>
            </div>
          </form>
        )}

        {/* Step 3: Supplier Import (Excel or CSV) */}
        {step === 3 && (
          <form
            onSubmit={uploadMode === 'excel' ? handleExcelUpload : handleCSVUpload}
            className="signup-form"
          >
            <h2>Import Your Suppliers</h2>

            <p className="step-description">
              Add your supplier data so DisruptIQ can map your supply chain topology.
            </p>

            {/* Mode toggle */}
            <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
              <button
                type="button"
                className={`btn btn-sm ${uploadMode === 'excel' ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => { setUploadMode('excel'); setError(null) }}
              >
                Excel Upload (Recommended)
              </button>
              <button
                type="button"
                className={`btn btn-sm ${uploadMode === 'csv' ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => { setUploadMode('csv'); setError(null) }}
              >
                CSV Import
              </button>
            </div>

            {/* Excel mode */}
            {uploadMode === 'excel' && (
              <>
                <div className="csv-helper" style={{ marginBottom: 16 }}>
                  <h4>Step 1 — Download the template</h4>
                  <p style={{ marginBottom: 12 }}>
                    Download the Excel template, fill in your supplier details (it includes
                    example rows and a notes guide), then upload it below.
                  </p>
                  <button
                    type="button"
                    className="btn btn-secondary btn-sm"
                    onClick={handleDownloadTemplate}
                    disabled={downloadingTemplate}
                  >
                    {downloadingTemplate ? 'Downloading...' : '⬇ Download Excel Template (.xlsx)'}
                  </button>
                </div>

                <div className="csv-section">
                  <h4 style={{ marginBottom: 10 }}>Step 2 — Upload your filled file</h4>
                  <div className="csv-upload">
                    <label htmlFor="xlsx-file" className="file-label">
                      <span>{xlsxFile ? `📄 ${xlsxFile.name}` : '📁 Click to select Excel file (.xlsx)'}</span>
                      <input
                        id="xlsx-file"
                        type="file"
                        accept=".xlsx,.xls"
                        onChange={(e) => setXlsxFile(e.target.files?.[0] || null)}
                      />
                    </label>
                  </div>
                </div>
              </>
            )}

            {/* CSV mode */}
            {uploadMode === 'csv' && (
              <>
                <div className="csv-section">
                  <div className="csv-upload">
                    <label htmlFor="csv-file" className="file-label">
                      <span>📁 Click to select CSV file</span>
                      <input
                        id="csv-file"
                        type="file"
                        accept=".csv"
                        onChange={handleCSVFileUpload}
                      />
                    </label>
                  </div>

                  <div className="csv-divider">or paste CSV data below:</div>

                  <textarea
                    value={csvContent}
                    onChange={(e) => setCsvContent(e.target.value)}
                    placeholder={csvExample}
                    rows="8"
                  ></textarea>
                </div>

                <div className="csv-helper">
                  <h4>CSV Format:</h4>
                  <code>{csvExample}</code>
                  <p>Valid locations: Chennai, Coimbatore, Tamil Nadu, Pune, Mumbai, Bengaluru, Karnataka, Delhi, NCR, Maharashtra, Rajasthan, Kolkata</p>
                </div>
              </>
            )}

            {csvWarnings.length > 0 && (
              <div className="warnings">
                <h4>⚠️ Warnings:</h4>
                {csvWarnings.map((w, i) => (
                  <p key={i}>{w}</p>
                ))}
              </div>
            )}

            <div className="form-actions">
              <button type="button" className="btn btn-secondary" onClick={() => setStep(2)}>
                Back
              </button>
              <button type="submit" className="btn btn-primary btn-lg" disabled={loading}>
                {loading ? 'Importing...' : 'Create Dashboard'}
              </button>
            </div>

            <p className="skip-hint">
              Can't prepare files now? <button type="button" onClick={() => navigate(`/dashboard/${clientId}`)} className="link-button">Skip and start exploring</button>
            </p>
          </form>
        )}
      </div>
    </div>
    </>
  )
}
