"""DisruptIQ V2 — Demo seed data.

Only ONE seed client: "demo".
Represents VistaTech Industries — an Indian automotive-electronics manufacturer
headquartered in Pune with a mixed India + global supply chain.
ifb / tata_motors / global_demo removed entirely.
"""

# ── Cascade zone overlap map ─────────────────────────────────────────────────
CASCADE_ZONE_MAP = {
    # India
    "Chennai":      ["Chennai", "Tamil Nadu", "Thiruvallur", "Kanchipuram", "Chengalpattu"],
    "Tamil Nadu":   ["Tamil Nadu", "Chennai", "Coimbatore", "Madurai", "Salem"],
    "Coimbatore":   ["Coimbatore", "Tamil Nadu", "Erode", "Tiruppur"],
    "Mumbai":       ["Mumbai", "Maharashtra", "Navi Mumbai", "Thane"],
    "Maharashtra":  ["Maharashtra", "Mumbai", "Pune", "Nashik"],
    "Pune":         ["Pune", "Maharashtra", "Pimpri-Chinchwad"],
    "Bengaluru":    ["Bengaluru", "Karnataka", "Mysuru"],
    "Karnataka":    ["Karnataka", "Bengaluru", "Mangaluru", "Hubli"],
    "Delhi":        ["Delhi", "NCR", "Gurugram", "Noida", "Faridabad"],
    "NCR":          ["NCR", "Delhi", "Gurugram", "Noida", "Faridabad"],
    "Hyderabad":    ["Hyderabad", "Telangana", "Secunderabad"],
    "Ahmedabad":    ["Ahmedabad", "Gujarat", "Surat", "Vadodara"],
    "Kolkata":      ["Kolkata", "West Bengal", "Howrah", "Haldia"],
    "Jamshedpur":   ["Jamshedpur", "Jharkhand", "Bokaro"],
    # Global
    "Shanghai":     ["Shanghai", "Jiangsu", "Zhejiang"],
    "Shenzhen":     ["Shenzhen", "Guangdong", "Guangzhou"],
    "Singapore":    ["Singapore"],
    "Dubai":        ["Dubai", "UAE", "Abu Dhabi"],
    "Frankfurt":    ["Frankfurt", "Germany", "Hamburg"],
    "Rotterdam":    ["Rotterdam", "Netherlands", "Amsterdam"],
    "Los Angeles":  ["Los Angeles", "California"],
    "Seoul":        ["Seoul", "South Korea", "Busan"],
    "Tokyo":        ["Tokyo", "Japan", "Osaka"],
    "Taipei":       ["Taipei", "Taiwan"],
    "Mexico City":  ["Mexico City", "Mexico"],
}

# ── Demo supplier dataset ─────────────────────────────────────────────────────
# VistaTech Industries — Pune HQ, Automotive Electronics
# 18 Indian suppliers + 12 global suppliers = 30 total
CLIENT_SUPPLIER_DATABASES = {
    "demo": [
        # ── India: South ────────────────────────────────────────────────────
        {
            "id": "D-IND-001",
            "name": "Precision Circuits Chennai",
            "zone": "Chennai",
            "buffer_stock_days": 12,
            "sites": 3,
            "reliability": 91,
            "categories": ["PCB Assemblies", "Control Electronics"],
            "proximity_score": 8,
        },
        {
            "id": "D-IND-002",
            "name": "Coromandel Auto Forgings",
            "zone": "Chennai",
            "buffer_stock_days": 3,
            "sites": 1,
            "reliability": 72,
            "categories": ["Forged Crankshafts", "Structural Parts"],
            "proximity_score": 9,
        },
        {
            "id": "D-IND-003",
            "name": "SureTech Sensors — Tamil Nadu",
            "zone": "Tamil Nadu",
            "buffer_stock_days": 9,
            "sites": 2,
            "reliability": 84,
            "categories": ["Automotive Sensors", "ADAS Modules"],
            "proximity_score": 7,
        },
        {
            "id": "D-IND-004",
            "name": "Kovai Motors & Drives",
            "zone": "Coimbatore",
            "buffer_stock_days": 18,
            "sites": 2,
            "reliability": 88,
            "categories": ["Electric Motors", "Drive Systems"],
            "proximity_score": 6,
        },
        {
            "id": "D-IND-005",
            "name": "Infotech Semiconductors Bengaluru",
            "zone": "Bengaluru",
            "buffer_stock_days": 14,
            "sites": 4,
            "reliability": 95,
            "categories": ["Microcontrollers", "Power ICs"],
            "proximity_score": 4,
        },
        {
            "id": "D-IND-006",
            "name": "Deccan Precision Engineering",
            "zone": "Bengaluru",
            "buffer_stock_days": 7,
            "sites": 2,
            "reliability": 80,
            "categories": ["Precision Machined Parts", "Aluminium Castings"],
            "proximity_score": 5,
        },
        {
            "id": "D-IND-007",
            "name": "Cyberabad Plastics & Polymers",
            "zone": "Hyderabad",
            "buffer_stock_days": 21,
            "sites": 3,
            "reliability": 90,
            "categories": ["Engineering Plastics", "Polymer Components"],
            "proximity_score": 3,
        },
        {
            "id": "D-IND-008",
            "name": "Telangana Wire Harness Co",
            "zone": "Hyderabad",
            "buffer_stock_days": 5,
            "sites": 1,
            "reliability": 76,
            "categories": ["Wiring Harness", "Connectors"],
            "proximity_score": 8,
        },
        # ── India: West ─────────────────────────────────────────────────────
        {
            "id": "D-IND-009",
            "name": "Western Auto Components Pune",
            "zone": "Pune",
            "buffer_stock_days": 25,
            "sites": 5,
            "reliability": 96,
            "categories": ["Suspension Parts", "Brake Assemblies"],
            "proximity_score": 2,
        },
        {
            "id": "D-IND-010",
            "name": "Bharat Steel Stampings",
            "zone": "Pune",
            "buffer_stock_days": 10,
            "sites": 2,
            "reliability": 85,
            "categories": ["Sheet Metal Stampings", "Body Panels"],
            "proximity_score": 4,
        },
        {
            "id": "D-IND-011",
            "name": "JNPT Chemicals & Coatings",
            "zone": "Mumbai",
            "buffer_stock_days": 16,
            "sites": 3,
            "reliability": 89,
            "categories": ["Specialty Chemicals", "Surface Coatings"],
            "proximity_score": 5,
        },
        {
            "id": "D-IND-012",
            "name": "Gujarat Polymers Ltd",
            "zone": "Ahmedabad",
            "buffer_stock_days": 30,
            "sites": 4,
            "reliability": 93,
            "categories": ["Raw Polymers", "Rubber Compounds"],
            "proximity_score": 3,
        },
        # ── India: North ────────────────────────────────────────────────────
        {
            "id": "D-IND-013",
            "name": "Delhi NCR Electronics Hub",
            "zone": "Delhi",
            "buffer_stock_days": 11,
            "sites": 3,
            "reliability": 87,
            "categories": ["Display Modules", "Infotainment Systems"],
            "proximity_score": 3,
        },
        {
            "id": "D-IND-014",
            "name": "Gurugram Precision Bearings",
            "zone": "NCR",
            "buffer_stock_days": 20,
            "sites": 2,
            "reliability": 92,
            "categories": ["Bearings", "Seals & Gaskets"],
            "proximity_score": 2,
        },
        {
            "id": "D-IND-015",
            "name": "Ludhiana Fasteners & Bolts",
            "zone": "Punjab",
            "buffer_stock_days": 35,
            "sites": 2,
            "reliability": 94,
            "categories": ["Fasteners", "Machined Bolts"],
            "proximity_score": 1,
        },
        # ── India: East ─────────────────────────────────────────────────────
        {
            "id": "D-IND-016",
            "name": "Tata Steel Supplies Jamshedpur",
            "zone": "Jamshedpur",
            "buffer_stock_days": 22,
            "sites": 3,
            "reliability": 97,
            "categories": ["High-Grade Steel", "Alloy Steel"],
            "proximity_score": 2,
        },
        {
            "id": "D-IND-017",
            "name": "Bengal Industrial Aggregates",
            "zone": "Kolkata",
            "buffer_stock_days": 8,
            "sites": 1,
            "reliability": 78,
            "categories": ["Raw Materials", "Industrial Aggregates"],
            "proximity_score": 6,
        },
        {
            "id": "D-IND-018",
            "name": "Odisha Aluminium Extrusions",
            "zone": "Bhubaneswar",
            "buffer_stock_days": 15,
            "sites": 2,
            "reliability": 83,
            "categories": ["Aluminium Extrusions", "Heat Sinks"],
            "proximity_score": 5,
        },
        # ── Global: East Asia ────────────────────────────────────────────────
        {
            "id": "D-GLB-001",
            "name": "CATL Battery Cells Shanghai",
            "zone": "Shanghai",
            "buffer_stock_days": 6,
            "sites": 2,
            "reliability": 93,
            "categories": ["EV Battery Cells", "Battery Packs"],
            "proximity_score": 9,
        },
        {
            "id": "D-GLB-002",
            "name": "Yangtze PCB Manufacturing",
            "zone": "Shanghai",
            "buffer_stock_days": 4,
            "sites": 1,
            "reliability": 79,
            "categories": ["Multilayer PCBs", "Flex Circuits"],
            "proximity_score": 9,
        },
        {
            "id": "D-GLB-003",
            "name": "Foxlink Electronics Shenzhen",
            "zone": "Shenzhen",
            "buffer_stock_days": 7,
            "sites": 3,
            "reliability": 88,
            "categories": ["Connectors", "Cable Assemblies"],
            "proximity_score": 8,
        },
        {
            "id": "D-GLB-004",
            "name": "TSMC Wafer Supply Taipei",
            "zone": "Taipei",
            "buffer_stock_days": 10,
            "sites": 2,
            "reliability": 96,
            "categories": ["Semiconductor Wafers", "Foundry ICs"],
            "proximity_score": 7,
        },
        {
            "id": "D-GLB-005",
            "name": "Samsung Display Seoul",
            "zone": "Seoul",
            "buffer_stock_days": 12,
            "sites": 2,
            "reliability": 94,
            "categories": ["OLED Panels", "Display Assemblies"],
            "proximity_score": 6,
        },
        {
            "id": "D-GLB-006",
            "name": "Denso Robotics Components Tokyo",
            "zone": "Tokyo",
            "buffer_stock_days": 15,
            "sites": 3,
            "reliability": 97,
            "categories": ["Robotics Arms", "Precision Actuators"],
            "proximity_score": 5,
        },
        {
            "id": "D-GLB-007",
            "name": "Pacific Maritime Logistics Singapore",
            "zone": "Singapore",
            "buffer_stock_days": 5,
            "sites": 2,
            "reliability": 91,
            "categories": ["Logistics", "Cold-Chain Freight"],
            "proximity_score": 8,
        },
        # ── Global: Middle East & Europe ─────────────────────────────────────
        {
            "id": "D-GLB-008",
            "name": "Emirates Aluminium Dubai",
            "zone": "Dubai",
            "buffer_stock_days": 20,
            "sites": 2,
            "reliability": 85,
            "categories": ["Primary Aluminium", "Alloy Ingots"],
            "proximity_score": 5,
        },
        {
            "id": "D-GLB-009",
            "name": "Bosch Industrial Sensors Frankfurt",
            "zone": "Frankfurt",
            "buffer_stock_days": 18,
            "sites": 4,
            "reliability": 95,
            "categories": ["Industrial Sensors", "IoT Modules"],
            "proximity_score": 4,
        },
        {
            "id": "D-GLB-010",
            "name": "Rotterdam Port Chemicals",
            "zone": "Rotterdam",
            "buffer_stock_days": 14,
            "sites": 3,
            "reliability": 87,
            "categories": ["Specialty Chemicals", "Adhesives"],
            "proximity_score": 6,
        },
        # ── Global: Americas ────────────────────────────────────────────────
        {
            "id": "D-GLB-011",
            "name": "Advanced Composites Los Angeles",
            "zone": "Los Angeles",
            "buffer_stock_days": 22,
            "sites": 2,
            "reliability": 82,
            "categories": ["Carbon Fibre Composites", "Structural Panels"],
            "proximity_score": 3,
        },
        {
            "id": "D-GLB-012",
            "name": "Honeywell Precision Electronics Mexico",
            "zone": "Mexico City",
            "buffer_stock_days": 17,
            "sites": 2,
            "reliability": 86,
            "categories": ["Avionics Parts", "Precision Electronics"],
            "proximity_score": 4,
        },
    ],
}


def get_suppliers_for_client(client_id: str = "demo") -> list:
    """Return suppliers for a seed client. Only 'demo' is a valid seed client ID."""
    return CLIENT_SUPPLIER_DATABASES.get(client_id, [])


# Backward-compat alias used by main.py
SUPPLIERS = get_suppliers_for_client("demo")

# ── Demo scenario templates ──────────────────────────────────────────────────
DEMO_SCENARIOS = [
    {
        "id": "scenario_chennai_cyclone",
        "name": "Cyclone Kiran — Chennai Coastal Disruption",
        "description": "Category 4 cyclone makes landfall near Chennai. Port suspended 72h. PCB and forging suppliers directly impacted.",
        "location": "Chennai",
        "type": "Cyclone",
        "severity_expected": 8,
    },
    {
        "id": "scenario_taiwan_semiconductor",
        "name": "Taiwan Strait Tension — Semiconductor Supply Shock",
        "description": "Geopolitical escalation disrupts TSMC wafer shipments from Taipei and cascades to Shenzhen and Shanghai.",
        "location": "Taipei",
        "type": "Geopolitical Disruption",
        "severity_expected": 9,
    },
    {
        "id": "scenario_mumbai_strike",
        "name": "JNPT Port Worker Strike — Mumbai",
        "description": "Industrial action at Jawaharlal Nehru Port halts all container operations. 60% of west-coast imports delayed 48-72 hours.",
        "location": "Mumbai",
        "type": "Industrial Action",
        "severity_expected": 7,
    },
    {
        "id": "scenario_shanghai_lockdown",
        "name": "Shanghai Industrial Zone Lockdown",
        "description": "Regulatory lockdown across Shanghai industrial districts. EV battery cell and PCB suppliers face 2-week production freeze.",
        "location": "Shanghai",
        "type": "Regulatory Shutdown",
        "severity_expected": 8,
    },
    {
        "id": "scenario_eu_port_strike",
        "name": "Rotterdam Port Strike — European Supply Freeze",
        "description": "Coordinated dock-worker strike shuts Rotterdam for 5 days. Specialty chemical and sensor shipments from Europe delayed.",
        "location": "Rotterdam",
        "type": "Industrial Action",
        "severity_expected": 7,
    },
    {
        "id": "scenario_jamshedpur_flood",
        "name": "Jharkhand Floods — Steel Supply Disruption",
        "description": "Monsoon flooding cuts road access to Jamshedpur steel plants. High-grade steel shipments to Pune assembly suspended.",
        "location": "Jamshedpur",
        "type": "Flood",
        "severity_expected": 6,
    },
]

# ── Stage-1 memory (for swarm recall) ───────────────────────────────────────
SEED_MEMORY = [
    {
        "memory_id": "MEM-CHN-001",
        "stage": 2,
        "event_id": "EVT-HIST-001",
        "event_type": "Cyclone",
        "geography": "Chennai",
        "supplier_id": "D-IND-001",
        "supplier_name": "Precision Circuits Chennai",
        "predicted_risk_score": 82,
        "predicted_demand_shift": 32.0,
        "actual_demand_shift": 36.5,
        "actual_outcome": "Full disruption 5 days; PCB supply bridge from Bengaluru activated",
        "option_selected": "Air-freight from Bengaluru",
        "resolution_date": "2025-11-09",
        "learning_signal": "Cyclone demand impact underestimated +4.5%; coastal-storm multiplier needs upward recalibration",
        "variance": "+4.5% demand vs forecast",
        "timestamp_utc": "2025-11-09T18:00:00Z",
    },
    {
        "memory_id": "MEM-SHA-001",
        "stage": 2,
        "event_id": "EVT-HIST-002",
        "event_type": "Regulatory Shutdown",
        "geography": "Shanghai",
        "supplier_id": "D-GLB-001",
        "supplier_name": "CATL Battery Cells Shanghai",
        "predicted_risk_score": 78,
        "predicted_demand_shift": 28.0,
        "actual_demand_shift": 24.0,
        "actual_outcome": "14-day production freeze; alternate South Korea battery cells activated within 72h",
        "option_selected": "Switch to Samsung SDI alternate Seoul",
        "resolution_date": "2025-12-15",
        "learning_signal": "Regulatory shutdown demand impact slightly over-predicted; alternate supplier activation effective",
        "variance": "-4.0% demand vs forecast",
        "timestamp_utc": "2025-12-15T10:00:00Z",
    },
]

# ── ZONE_COORDINATES ─────────────────────────────────────────────────────────
ZONE_COORDINATES = {
    # ── South India ──────────────────────────────────────────────────────────
    "Tamil Nadu":        {"lat": 11.13, "lon": 78.66},
    "Chennai":           {"lat": 13.08, "lon": 80.27},
    "Coimbatore":        {"lat": 11.02, "lon": 76.96},
    "Madurai":           {"lat":  9.93, "lon": 78.12},
    "Salem":             {"lat": 11.65, "lon": 78.15},
    "Tiruchirappalli":   {"lat": 10.80, "lon": 78.69},
    "Trichy":            {"lat": 10.80, "lon": 78.69},
    "Tirunelveli":       {"lat":  8.72, "lon": 77.70},
    "Vellore":           {"lat": 12.92, "lon": 79.13},
    "Erode":             {"lat": 11.34, "lon": 77.72},
    "Tiruppur":          {"lat": 11.11, "lon": 77.34},
    "Kanchipuram":       {"lat": 12.83, "lon": 79.70},
    "Thiruvallur":       {"lat": 13.14, "lon": 79.91},
    "Chengalpattu":      {"lat": 12.69, "lon": 79.98},
    "Pondicherry":       {"lat": 11.93, "lon": 79.83},
    "Puducherry":        {"lat": 11.93, "lon": 79.83},
    "Karnataka":         {"lat": 15.32, "lon": 75.71},
    "Bengaluru":         {"lat": 12.97, "lon": 77.59},
    "Bangalore":         {"lat": 12.97, "lon": 77.59},
    "Mysuru":            {"lat": 12.30, "lon": 76.65},
    "Mysore":            {"lat": 12.30, "lon": 76.65},
    "Mangaluru":         {"lat": 12.87, "lon": 74.84},
    "Mangalore":         {"lat": 12.87, "lon": 74.84},
    "Hubli":             {"lat": 15.36, "lon": 75.12},
    "Hubballi":          {"lat": 15.36, "lon": 75.12},
    "Dharwad":           {"lat": 15.46, "lon": 75.01},
    "Belgaum":           {"lat": 15.85, "lon": 74.50},
    "Belagavi":          {"lat": 15.85, "lon": 74.50},
    "Kerala":            {"lat":  9.97, "lon": 76.24},
    "Thiruvananthapuram":{"lat":  8.52, "lon": 76.93},
    "Trivandrum":        {"lat":  8.52, "lon": 76.93},
    "Kochi":             {"lat":  9.93, "lon": 76.26},
    "Cochin":            {"lat":  9.93, "lon": 76.26},
    "Kozhikode":         {"lat": 11.25, "lon": 75.78},
    "Calicut":           {"lat": 11.25, "lon": 75.78},
    "Thrissur":          {"lat": 10.53, "lon": 76.21},
    "Kollam":            {"lat":  8.89, "lon": 76.61},
    "Kannur":            {"lat": 11.87, "lon": 75.37},
    "Palakkad":          {"lat": 10.78, "lon": 76.65},
    "Andhra Pradesh":    {"lat": 15.91, "lon": 79.74},
    "Visakhapatnam":     {"lat": 17.69, "lon": 83.22},
    "Vizag":             {"lat": 17.69, "lon": 83.22},
    "Vijayawada":        {"lat": 16.51, "lon": 80.62},
    "Guntur":            {"lat": 16.30, "lon": 80.44},
    "Nellore":           {"lat": 14.44, "lon": 79.99},
    "Tirupati":          {"lat": 13.63, "lon": 79.42},
    "Rajahmundry":       {"lat": 17.00, "lon": 81.78},
    "Kurnool":           {"lat": 15.83, "lon": 78.04},
    "Telangana":         {"lat": 18.11, "lon": 79.02},
    "Hyderabad":         {"lat": 17.38, "lon": 78.48},
    "Secunderabad":      {"lat": 17.44, "lon": 78.50},
    "Warangal":          {"lat": 17.97, "lon": 79.59},
    "Karimnagar":        {"lat": 18.44, "lon": 79.13},
    "Nizamabad":         {"lat": 18.67, "lon": 78.09},
    # ── West India ───────────────────────────────────────────────────────────
    "Maharashtra":       {"lat": 19.75, "lon": 75.71},
    "Mumbai":            {"lat": 19.08, "lon": 72.88},
    "Navi Mumbai":       {"lat": 19.03, "lon": 73.02},
    "Thane":             {"lat": 19.22, "lon": 72.98},
    "Pune":              {"lat": 18.52, "lon": 73.86},
    "Pimpri-Chinchwad":  {"lat": 18.62, "lon": 73.80},
    "Nashik":            {"lat": 19.99, "lon": 73.79},
    "Aurangabad":        {"lat": 19.88, "lon": 75.34},
    "Chhatrapati Sambhajinagar": {"lat": 19.88, "lon": 75.34},
    "Nagpur":            {"lat": 21.15, "lon": 79.09},
    "Solapur":           {"lat": 17.68, "lon": 75.91},
    "Kolhapur":          {"lat": 16.70, "lon": 74.22},
    "Satara":            {"lat": 17.69, "lon": 74.00},
    "Raigad":            {"lat": 18.51, "lon": 73.18},
    "Gujarat":           {"lat": 22.26, "lon": 71.19},
    "Ahmedabad":         {"lat": 23.02, "lon": 72.57},
    "Surat":             {"lat": 21.17, "lon": 72.83},
    "Vadodara":          {"lat": 22.31, "lon": 73.19},
    "Baroda":            {"lat": 22.31, "lon": 73.19},
    "Rajkot":            {"lat": 22.30, "lon": 70.80},
    "Bhavnagar":         {"lat": 21.76, "lon": 72.15},
    "Jamnagar":          {"lat": 22.47, "lon": 70.07},
    "Gandhinagar":       {"lat": 23.22, "lon": 72.65},
    "Anand":             {"lat": 22.56, "lon": 72.95},
    "Bharuch":           {"lat": 21.71, "lon": 72.99},
    "Morbi":             {"lat": 22.82, "lon": 70.84},
    "Mundra":            {"lat": 22.84, "lon": 69.72},
    "Kandla":            {"lat": 23.02, "lon": 70.22},
    "Kutch":             {"lat": 23.73, "lon": 69.86},
    "Bhuj":              {"lat": 23.25, "lon": 69.67},
    "Rajasthan":         {"lat": 27.02, "lon": 74.22},
    "Jaipur":            {"lat": 26.91, "lon": 75.79},
    "Jodhpur":           {"lat": 26.29, "lon": 73.02},
    "Udaipur":           {"lat": 24.58, "lon": 73.68},
    "Kota":              {"lat": 25.18, "lon": 75.84},
    "Ajmer":             {"lat": 26.45, "lon": 74.64},
    "Bikaner":           {"lat": 28.01, "lon": 73.31},
    "Alwar":             {"lat": 27.56, "lon": 76.61},
    "Goa":               {"lat": 15.30, "lon": 74.12},
    "Panaji":            {"lat": 15.50, "lon": 73.83},
    # ── North India ──────────────────────────────────────────────────────────
    "Delhi":             {"lat": 28.61, "lon": 77.21},
    "New Delhi":         {"lat": 28.61, "lon": 77.21},
    "NCR":               {"lat": 28.45, "lon": 77.50},
    "Gurugram":          {"lat": 28.46, "lon": 77.03},
    "Gurgaon":           {"lat": 28.46, "lon": 77.03},
    "Noida":             {"lat": 28.54, "lon": 77.39},
    "Faridabad":         {"lat": 28.41, "lon": 77.31},
    "Ghaziabad":         {"lat": 28.67, "lon": 77.43},
    "Greater Noida":     {"lat": 28.47, "lon": 77.50},
    "Haryana":           {"lat": 29.06, "lon": 76.09},
    "Chandigarh":        {"lat": 30.73, "lon": 76.78},
    "Ambala":            {"lat": 30.38, "lon": 76.78},
    "Hisar":             {"lat": 29.15, "lon": 75.72},
    "Rohtak":            {"lat": 28.90, "lon": 76.59},
    "Panipat":           {"lat": 29.39, "lon": 76.97},
    "Sonipat":           {"lat": 29.00, "lon": 77.00},
    "Karnal":            {"lat": 29.69, "lon": 76.99},
    "Punjab":            {"lat": 31.15, "lon": 75.34},
    "Ludhiana":          {"lat": 30.90, "lon": 75.85},
    "Amritsar":          {"lat": 31.63, "lon": 74.87},
    "Jalandhar":         {"lat": 31.32, "lon": 75.58},
    "Patiala":           {"lat": 30.34, "lon": 76.39},
    "Bathinda":          {"lat": 30.21, "lon": 74.95},
    "Uttar Pradesh":     {"lat": 26.85, "lon": 80.91},
    "Lucknow":           {"lat": 26.85, "lon": 80.95},
    "Kanpur":            {"lat": 26.47, "lon": 80.33},
    "Agra":              {"lat": 27.18, "lon": 78.01},
    "Varanasi":          {"lat": 25.32, "lon": 83.00},
    "Prayagraj":         {"lat": 25.43, "lon": 81.85},
    "Meerut":            {"lat": 28.98, "lon": 77.71},
    "Mathura":           {"lat": 27.49, "lon": 77.67},
    "Bareilly":          {"lat": 28.36, "lon": 79.41},
    "Gorakhpur":         {"lat": 26.76, "lon": 83.37},
    "Uttarakhand":       {"lat": 30.07, "lon": 79.07},
    "Dehradun":          {"lat": 30.32, "lon": 78.03},
    "Haridwar":          {"lat": 29.95, "lon": 78.16},
    "Roorkee":           {"lat": 29.87, "lon": 77.89},
    "Himachal Pradesh":  {"lat": 31.90, "lon": 77.11},
    "Shimla":            {"lat": 31.10, "lon": 77.17},
    "Baddi":             {"lat": 30.96, "lon": 76.79},
    "Jammu":             {"lat": 32.74, "lon": 74.86},
    "Srinagar":          {"lat": 34.08, "lon": 74.80},
    # ── Central India ────────────────────────────────────────────────────────
    "Madhya Pradesh":    {"lat": 22.97, "lon": 78.65},
    "Bhopal":            {"lat": 23.26, "lon": 77.40},
    "Indore":            {"lat": 22.72, "lon": 75.86},
    "Jabalpur":          {"lat": 23.18, "lon": 79.94},
    "Gwalior":           {"lat": 26.22, "lon": 78.18},
    "Ujjain":            {"lat": 23.18, "lon": 75.78},
    "Pithampur":         {"lat": 22.61, "lon": 75.70},
    "Chhattisgarh":      {"lat": 21.27, "lon": 81.86},
    "Raipur":            {"lat": 21.25, "lon": 81.63},
    "Bhilai":            {"lat": 21.21, "lon": 81.43},
    # ── East India ───────────────────────────────────────────────────────────
    "West Bengal":       {"lat": 22.99, "lon": 87.85},
    "Kolkata":           {"lat": 22.57, "lon": 88.36},
    "Howrah":            {"lat": 22.59, "lon": 88.31},
    "Haldia":            {"lat": 22.03, "lon": 88.07},
    "Asansol":           {"lat": 23.68, "lon": 86.98},
    "Durgapur":          {"lat": 23.55, "lon": 87.32},
    "Siliguri":          {"lat": 26.72, "lon": 88.43},
    "Bihar":             {"lat": 25.09, "lon": 85.31},
    "Patna":             {"lat": 25.60, "lon": 85.14},
    "Muzaffarpur":       {"lat": 26.12, "lon": 85.39},
    "Jharkhand":         {"lat": 23.61, "lon": 85.28},
    "Ranchi":            {"lat": 23.34, "lon": 85.31},
    "Jamshedpur":        {"lat": 22.80, "lon": 86.20},
    "Dhanbad":           {"lat": 23.80, "lon": 86.44},
    "Bokaro":            {"lat": 23.67, "lon": 86.15},
    "Odisha":            {"lat": 20.52, "lon": 85.09},
    "Bhubaneswar":       {"lat": 20.30, "lon": 85.82},
    "Cuttack":           {"lat": 20.46, "lon": 85.88},
    "Rourkela":          {"lat": 22.26, "lon": 84.86},
    "Paradip":           {"lat": 20.32, "lon": 86.61},
    "Balasore":          {"lat": 21.49, "lon": 86.93},
    # ── Northeast India ──────────────────────────────────────────────────────
    "Assam":             {"lat": 26.20, "lon": 92.94},
    "Guwahati":          {"lat": 26.14, "lon": 91.74},
    "Dibrugarh":         {"lat": 27.49, "lon": 94.91},
    "Meghalaya":         {"lat": 25.47, "lon": 91.37},
    "Shillong":          {"lat": 25.57, "lon": 91.89},
    "Nagaland":          {"lat": 26.16, "lon": 94.61},
    "Kohima":            {"lat": 25.67, "lon": 94.11},
    "Manipur":           {"lat": 24.66, "lon": 93.91},
    "Imphal":            {"lat": 24.82, "lon": 93.94},
    "Mizoram":           {"lat": 23.16, "lon": 92.94},
    "Tripura":           {"lat": 23.94, "lon": 91.99},
    "Agartala":          {"lat": 23.83, "lon": 91.28},
    "Arunachal Pradesh": {"lat": 28.22, "lon": 94.73},
    "Sikkim":            {"lat": 27.53, "lon": 88.51},
    # ── Generic Indian regions ───────────────────────────────────────────────
    "North India":       {"lat": 28.00, "lon": 77.00},
    "South India":       {"lat": 13.00, "lon": 79.00},
    "East India":        {"lat": 22.00, "lon": 86.00},
    "West India":        {"lat": 22.00, "lon": 73.00},
    "Central India":     {"lat": 22.00, "lon": 79.00},
    "Pan India":         {"lat": 22.00, "lon": 79.00},
    # ── East Asia ────────────────────────────────────────────────────────────
    "China":             {"lat": 35.86, "lon": 104.19},
    "Shanghai":          {"lat": 31.23, "lon": 121.47},
    "Shenzhen":          {"lat": 22.54, "lon": 114.06},
    "Guangzhou":         {"lat": 23.13, "lon": 113.26},
    "Guangdong":         {"lat": 23.13, "lon": 113.26},
    "Beijing":           {"lat": 39.90, "lon": 116.40},
    "Tianjin":           {"lat": 39.09, "lon": 117.20},
    "Chengdu":           {"lat": 30.57, "lon": 104.07},
    "Wuhan":             {"lat": 30.59, "lon": 114.31},
    "Nanjing":           {"lat": 32.06, "lon": 118.80},
    "Hangzhou":          {"lat": 30.25, "lon": 120.15},
    "Suzhou":            {"lat": 31.30, "lon": 120.61},
    "Taiwan":            {"lat": 23.70, "lon": 120.96},
    "Taipei":            {"lat": 25.03, "lon": 121.57},
    "Kaohsiung":         {"lat": 22.63, "lon": 120.30},
    "Japan":             {"lat": 36.20, "lon": 138.25},
    "Tokyo":             {"lat": 35.68, "lon": 139.69},
    "Osaka":             {"lat": 34.69, "lon": 135.50},
    "Nagoya":            {"lat": 35.18, "lon": 136.91},
    "Yokohama":          {"lat": 35.44, "lon": 139.64},
    "South Korea":       {"lat": 37.56, "lon": 126.97},
    "Seoul":             {"lat": 37.56, "lon": 126.97},
    "Busan":             {"lat": 35.10, "lon": 129.04},
    "Incheon":           {"lat": 37.45, "lon": 126.70},
    # ── Southeast Asia ───────────────────────────────────────────────────────
    "Singapore":         {"lat":  1.35, "lon": 103.82},
    "Malaysia":          {"lat":  4.21, "lon": 101.98},
    "Kuala Lumpur":      {"lat":  3.14, "lon": 101.69},
    "Thailand":          {"lat": 13.75, "lon": 100.52},
    "Bangkok":           {"lat": 13.75, "lon": 100.52},
    "Vietnam":           {"lat": 21.03, "lon": 105.85},
    "Ho Chi Minh City":  {"lat": 10.82, "lon": 106.63},
    "Hanoi":             {"lat": 21.03, "lon": 105.85},
    "Indonesia":         {"lat": -6.20, "lon": 106.82},
    "Jakarta":           {"lat": -6.20, "lon": 106.82},
    # ── South Asia ───────────────────────────────────────────────────────────
    "Bangladesh":        {"lat": 23.81, "lon": 90.41},
    "Dhaka":             {"lat": 23.81, "lon": 90.41},
    "Sri Lanka":         {"lat":  6.93, "lon": 79.85},
    "Colombo":           {"lat":  6.93, "lon": 79.85},
    # ── Middle East ──────────────────────────────────────────────────────────
    "UAE":               {"lat": 24.46, "lon": 54.37},
    "Dubai":             {"lat": 25.20, "lon": 55.27},
    "Abu Dhabi":         {"lat": 24.45, "lon": 54.38},
    "Saudi Arabia":      {"lat": 24.69, "lon": 46.72},
    "Riyadh":            {"lat": 24.69, "lon": 46.72},
    "Jeddah":            {"lat": 21.49, "lon": 39.19},
    "Turkey":            {"lat": 39.92, "lon": 32.85},
    "Istanbul":          {"lat": 41.01, "lon": 28.95},
    "Israel":            {"lat": 31.05, "lon": 34.85},
    "Tel Aviv":          {"lat": 32.09, "lon": 34.79},
    # ── Europe ───────────────────────────────────────────────────────────────
    "Germany":           {"lat": 51.17, "lon": 10.45},
    "Frankfurt":         {"lat": 50.11, "lon":  8.68},
    "Hamburg":           {"lat": 53.55, "lon":  9.99},
    "Munich":            {"lat": 48.14, "lon": 11.58},
    "Berlin":            {"lat": 52.52, "lon": 13.40},
    "Stuttgart":         {"lat": 48.78, "lon":  9.18},
    "Netherlands":       {"lat": 52.13, "lon":  5.29},
    "Rotterdam":         {"lat": 51.92, "lon":  4.48},
    "Amsterdam":         {"lat": 52.37, "lon":  4.90},
    "France":            {"lat": 46.23, "lon":  2.21},
    "Paris":             {"lat": 48.86, "lon":  2.35},
    "UK":                {"lat": 55.38, "lon": -3.44},
    "London":            {"lat": 51.51, "lon": -0.13},
    "Italy":             {"lat": 41.87, "lon": 12.57},
    "Milan":             {"lat": 45.46, "lon":  9.19},
    "Turin":             {"lat": 45.07, "lon":  7.69},
    "Spain":             {"lat": 40.46, "lon": -3.75},
    "Madrid":            {"lat": 40.42, "lon": -3.70},
    "Barcelona":         {"lat": 41.39, "lon":  2.16},
    "Sweden":            {"lat": 60.13, "lon": 18.64},
    "Stockholm":         {"lat": 59.33, "lon": 18.07},
    "Poland":            {"lat": 52.07, "lon": 19.48},
    "Warsaw":            {"lat": 52.23, "lon": 21.01},
    "Czech Republic":    {"lat": 49.82, "lon": 15.47},
    "Prague":            {"lat": 50.08, "lon": 14.44},
    "Hungary":           {"lat": 47.16, "lon": 19.50},
    "Budapest":          {"lat": 47.50, "lon": 19.04},
    "Switzerland":       {"lat": 46.82, "lon":  8.23},
    "Zurich":            {"lat": 47.38, "lon":  8.54},
    "Belgium":           {"lat": 50.50, "lon":  4.47},
    "Brussels":          {"lat": 50.85, "lon":  4.35},
    "Antwerp":           {"lat": 51.22, "lon":  4.40},
    # ── Americas ─────────────────────────────────────────────────────────────
    "USA":               {"lat": 37.09, "lon": -95.71},
    "New York":          {"lat": 40.71, "lon": -74.01},
    "Los Angeles":       {"lat": 34.05, "lon":-118.24},
    "Chicago":           {"lat": 41.88, "lon": -87.63},
    "Houston":           {"lat": 29.76, "lon": -95.37},
    "Dallas":            {"lat": 32.78, "lon": -96.80},
    "Detroit":           {"lat": 42.33, "lon": -83.05},
    "San Jose":          {"lat": 37.34, "lon":-121.89},
    "San Francisco":     {"lat": 37.77, "lon":-122.42},
    "Seattle":           {"lat": 47.61, "lon":-122.33},
    "Canada":            {"lat": 56.13, "lon":-106.35},
    "Toronto":           {"lat": 43.65, "lon": -79.38},
    "Vancouver":         {"lat": 49.28, "lon":-123.12},
    "Mexico":            {"lat": 23.63, "lon":-102.55},
    "Mexico City":       {"lat": 19.43, "lon": -99.13},
    "Monterrey":         {"lat": 25.69, "lon":-100.32},
    "Brazil":            {"lat":-14.24, "lon": -51.93},
    "Sao Paulo":         {"lat":-23.55, "lon": -46.63},
    "São Paulo":         {"lat":-23.55, "lon": -46.63},
    "Rio de Janeiro":    {"lat":-22.91, "lon": -43.17},
    "Argentina":         {"lat":-38.42, "lon": -63.62},
    "Buenos Aires":      {"lat":-34.60, "lon": -58.38},
    # ── Africa ───────────────────────────────────────────────────────────────
    "South Africa":      {"lat":-30.56, "lon": 22.94},
    "Johannesburg":      {"lat":-26.20, "lon": 28.04},
    "Cape Town":         {"lat":-33.93, "lon": 18.42},
    "Nigeria":           {"lat":  9.08, "lon":  8.67},
    "Lagos":             {"lat":  6.52, "lon":  3.38},
    "Egypt":             {"lat": 26.82, "lon": 30.80},
    "Cairo":             {"lat": 30.06, "lon": 31.25},
    "Kenya":             {"lat": -0.02, "lon": 37.91},
    "Nairobi":           {"lat": -1.29, "lon": 36.82},
    # ── Oceania ──────────────────────────────────────────────────────────────
    "Australia":         {"lat":-25.27, "lon": 133.78},
    "Sydney":            {"lat":-33.87, "lon": 151.21},
    "Melbourne":         {"lat":-37.81, "lon": 144.96},
    "Brisbane":          {"lat":-27.47, "lon": 153.02},
    "Perth":             {"lat":-31.95, "lon": 115.86},
    "New Zealand":       {"lat":-40.90, "lon": 174.89},
    "Auckland":          {"lat":-36.85, "lon": 174.76},
}


def zone_coordinates(zone: str) -> dict:
    """Return {lat, lon} for a zone name.
    Falls back through: exact → case-insensitive → substring → difflib → central India.
    """
    import difflib
    if not zone:
        return {"lat": 22.0, "lon": 79.0}
    z = zone.strip()
    if z in ZONE_COORDINATES:
        return ZONE_COORDINATES[z]
    z_lower = z.lower()
    for k, v in ZONE_COORDINATES.items():
        if k.lower() == z_lower:
            return v
    for k, v in ZONE_COORDINATES.items():
        if z_lower in k.lower() or k.lower() in z_lower:
            return v
    keys = list(ZONE_COORDINATES.keys())
    matches = difflib.get_close_matches(z, keys, n=1, cutoff=0.55)
    if not matches:
        low = difflib.get_close_matches(z_lower, [k.lower() for k in keys], n=1, cutoff=0.55)
        if low:
            matches = [k for k in keys if k.lower() == low[0]]
    if matches:
        return ZONE_COORDINATES[matches[0]]
    return {"lat": 22.0, "lon": 79.0}


# ── Logistics hubs (global ports) ────────────────────────────────────────────
LOGISTICS_HUBS = [
    {"id": "PORT-MAA", "name": "Chennai Port",          "type": "port", "lat": 13.10, "lon":  80.30},
    {"id": "PORT-NSA", "name": "JNPT Nhava Sheva",      "type": "port", "lat": 18.95, "lon":  72.95},
    {"id": "PORT-CCU", "name": "Kolkata Port",           "type": "port", "lat": 22.54, "lon":  88.31},
    {"id": "PORT-MUN", "name": "Mundra Port",            "type": "port", "lat": 22.84, "lon":  69.72},
    {"id": "PORT-SHA", "name": "Port of Shanghai",       "type": "port", "lat": 31.40, "lon": 121.50},
    {"id": "PORT-SIN", "name": "Port of Singapore",      "type": "port", "lat":  1.26, "lon": 103.82},
    {"id": "PORT-DXB", "name": "Jebel Ali Dubai",        "type": "port", "lat": 25.00, "lon":  55.07},
    {"id": "PORT-RTM", "name": "Port of Rotterdam",      "type": "port", "lat": 51.90, "lon":   4.15},
    {"id": "PORT-LAX", "name": "Port of Los Angeles",    "type": "port", "lat": 33.74, "lon":-118.27},
]

# ── Stage-2 memory records (R-05, R-09 reports) ──────────────────────────────
SEED_STAGE2_MEMORY = [
    {
        "id": "MEM-STAGE2-S001",
        "memory_id": "MEM-STAGE2-S001",
        "stage": 2,
        "event_id": "EVT-SEED-001",
        "client_id": "demo",
        "event_type": "Cyclone",
        "geography": "Chennai",
        "supplier_ids": ["D-IND-001", "D-IND-002"],
        "supplier_scores": [
            {"supplier_id": "D-IND-001", "supplier_name": "Precision Circuits Chennai",
             "score": 85, "predicted_risk_score": 85, "tier": "Critical", "zone": "Chennai", "memory_adjustment": 8.0},
            {"supplier_id": "D-IND-002", "supplier_name": "Coromandel Auto Forgings",
             "score": 91, "predicted_risk_score": 91, "tier": "Critical", "zone": "Chennai", "memory_adjustment": 6.0},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-IND-001", "score": 85, "memory_adjustment": 8.0},
            {"supplier_id": "D-IND-002", "score": 91, "memory_adjustment": 6.0},
        ],
        "predicted_demand_shift": 32.0,
        "actual_demand_shift": 36.5,
        "option_selected": "Air-freight from Bengaluru hub",
        "actual_outcome": "Cyclone caused 5-day full disruption; Bengaluru air-freight bridge activated day 2",
        "delivery_performance": "5-day outage; air-freight maintained 80% supply",
        "learning_signal": "Cyclone demand underestimated by 4.5%; coastal-storm multiplier needs upward recalibration",
        "severity_score": 8,
        "source": "IMD Cyclone Warning",
        "timestamp_utc": "2025-11-03T06:00:00Z",
        "resolution_timestamp_utc": "2025-11-09T18:00:00Z",
    },
    {
        "id": "MEM-STAGE2-S002",
        "memory_id": "MEM-STAGE2-S002",
        "stage": 2,
        "event_id": "EVT-SEED-002",
        "client_id": "demo",
        "event_type": "Regulatory Shutdown",
        "geography": "Shanghai",
        "supplier_ids": ["D-GLB-001", "D-GLB-002"],
        "supplier_scores": [
            {"supplier_id": "D-GLB-001", "supplier_name": "CATL Battery Cells Shanghai",
             "score": 78, "predicted_risk_score": 78, "tier": "High", "zone": "Shanghai", "memory_adjustment": -4.0},
            {"supplier_id": "D-GLB-002", "supplier_name": "Yangtze PCB Manufacturing",
             "score": 72, "predicted_risk_score": 72, "tier": "High", "zone": "Shanghai", "memory_adjustment": -2.0},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-GLB-001", "score": 78, "memory_adjustment": -4.0},
            {"supplier_id": "D-GLB-002", "score": 72, "memory_adjustment": -2.0},
        ],
        "predicted_demand_shift": 28.0,
        "actual_demand_shift": 24.0,
        "option_selected": "Switch to Samsung SDI alternate Seoul",
        "actual_outcome": "14-day freeze; alternate battery supply from Seoul activated within 72h",
        "delivery_performance": "72h gap bridged; on-time delivery maintained via alternate",
        "learning_signal": "Regulatory shutdown impact slightly over-predicted; alternate activation strategy validated",
        "severity_score": 8,
        "source": "Chinese Regulatory Monitor",
        "timestamp_utc": "2025-12-01T08:00:00Z",
        "resolution_timestamp_utc": "2025-12-15T10:00:00Z",
    },
    {
        "id": "MEM-STAGE2-S003",
        "memory_id": "MEM-STAGE2-S003",
        "stage": 2,
        "event_id": "EVT-SEED-003",
        "client_id": "demo",
        "event_type": "Industrial Action",
        "geography": "Mumbai",
        "supplier_ids": ["D-IND-011"],
        "supplier_scores": [
            {"supplier_id": "D-IND-011", "supplier_name": "JNPT Chemicals & Coatings",
             "score": 68, "predicted_risk_score": 68, "tier": "High", "zone": "Mumbai", "memory_adjustment": 2.0},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-IND-011", "score": 68, "memory_adjustment": 2.0},
        ],
        "predicted_demand_shift": 18.0,
        "actual_demand_shift": 16.5,
        "option_selected": "Activate Gujarat backup supplier",
        "actual_outcome": "Port strike resolved in 48h; Gujarat alternate covered the gap",
        "delivery_performance": "2-day delay; on-time delivery largely maintained",
        "learning_signal": "Industrial action demand impact slightly over-predicted; short-duration resolution common",
        "severity_score": 7,
        "source": "Port Authority Alert",
        "timestamp_utc": "2026-01-10T07:00:00Z",
        "resolution_timestamp_utc": "2026-01-12T16:00:00Z",
    },
    {
        "id": "MEM-STAGE2-S004",
        "memory_id": "MEM-STAGE2-S004",
        "stage": 2,
        "event_id": "EVT-SEED-004",
        "client_id": "demo",
        "event_type": "Flood",
        "geography": "Jamshedpur",
        "supplier_ids": ["D-IND-016"],
        "supplier_scores": [
            {"supplier_id": "D-IND-016", "supplier_name": "Tata Steel Supplies Jamshedpur",
             "score": 74, "predicted_risk_score": 74, "tier": "High", "zone": "Jamshedpur", "memory_adjustment": 3.0},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-IND-016", "score": 74, "memory_adjustment": 3.0},
        ],
        "predicted_demand_shift": 20.0,
        "actual_demand_shift": 18.0,
        "option_selected": "Temporary stockpile from Rourkela plant",
        "actual_outcome": "Flood receded in 3 days; Rourkela warehouse buffer absorbed the shortfall",
        "delivery_performance": "On-time delivery maintained via buffer stock",
        "learning_signal": "Flood scenario well-calibrated; buffer stock strategy validated for Jharkhand corridor",
        "severity_score": 6,
        "source": "CWC Flood Alert",
        "timestamp_utc": "2026-02-05T07:00:00Z",
        "resolution_timestamp_utc": "2026-02-08T15:00:00Z",
    },
    # Port Strike Mumbai cluster — three historical events so the MCF
    # calibration visibly engages when a demo trigger uses "Port Strike" + "Mumbai".
    {
        "id": "MEM-STAGE2-S005",
        "memory_id": "MEM-STAGE2-S005",
        "stage": 2,
        "event_id": "EVT-SEED-005",
        "client_id": "demo",
        "event_type": "Port Strike",
        "geography": "Mumbai",
        "supplier_ids": ["D-IND-011", "D-IND-012"],
        "supplier_scores": [
            {"supplier_id": "D-IND-011", "supplier_name": "JNPT Chemicals & Coatings",
             "score": 72, "predicted_risk_score": 72, "tier": "High", "zone": "Mumbai", "memory_adjustment": 4.0},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-IND-011", "score": 72, "memory_adjustment": 4.0},
        ],
        "predicted_demand_shift": -15.0,
        "actual_demand_shift": -11.5,
        "variance_demand": 3.5,
        "predicted_recovery_time_days": 3,
        "actual_recovery_time_days": 2.1,
        "variance_recovery": 0.9,
        "option_selected": "Re-route via Mundra port + Gujarat backup",
        "actual_outcome": "Strike resolved in 50h; Mundra absorbed 70% of diverted volume",
        "delivery_performance": "Recovered 2.1 days faster than predicted",
        "learning_signal": "Port Strike Mumbai impact over-predicted by 3.5% — alternate ports compress recovery",
        "severity_score": 7,
        "source": "Port Authority Alert",
        "timestamp_utc": "2025-01-15T10:30:00Z",
        "resolution_timestamp_utc": "2025-01-17T12:30:00Z",
    },
    {
        "id": "MEM-STAGE2-S006",
        "memory_id": "MEM-STAGE2-S006",
        "stage": 2,
        "event_id": "EVT-SEED-006",
        "client_id": "demo",
        "event_type": "Port Strike",
        "geography": "Mumbai",
        "supplier_ids": ["D-IND-013"],
        "supplier_scores": [
            {"supplier_id": "D-IND-013", "supplier_name": "Maharashtra Industrial Bearings",
             "score": 68, "predicted_risk_score": 68, "tier": "High", "zone": "Mumbai", "memory_adjustment": 3.2},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-IND-013", "score": 68, "memory_adjustment": 3.2},
        ],
        "predicted_demand_shift": -14.0,
        "actual_demand_shift": -10.8,
        "variance_demand": 3.2,
        "predicted_recovery_time_days": 3,
        "actual_recovery_time_days": 2.3,
        "variance_recovery": 0.7,
        "option_selected": "Activate Pune road-freight corridor",
        "actual_outcome": "Pune trucking absorbed the gap within 36h",
        "delivery_performance": "Recovered 0.7 days faster than predicted",
        "learning_signal": "Mumbai Port Strike: road-freight alternates compress recovery by ~25%",
        "severity_score": 7,
        "source": "Port Authority Alert",
        "timestamp_utc": "2025-02-08T14:20:00Z",
        "resolution_timestamp_utc": "2025-02-10T19:00:00Z",
    },
    {
        "id": "MEM-STAGE2-S007",
        "memory_id": "MEM-STAGE2-S007",
        "stage": 2,
        "event_id": "EVT-SEED-007",
        "client_id": "demo",
        "event_type": "Port Strike",
        "geography": "Mumbai",
        "supplier_ids": ["D-IND-014"],
        "supplier_scores": [
            {"supplier_id": "D-IND-014", "supplier_name": "Konkan Polymers Pvt",
             "score": 70, "predicted_risk_score": 70, "tier": "High", "zone": "Mumbai", "memory_adjustment": 3.9},
        ],
        "risk_scores_assigned": [
            {"supplier_id": "D-IND-014", "score": 70, "memory_adjustment": 3.9},
        ],
        "predicted_demand_shift": -16.0,
        "actual_demand_shift": -12.1,
        "variance_demand": 3.9,
        "predicted_recovery_time_days": 4,
        "actual_recovery_time_days": 3.0,
        "variance_recovery": 1.0,
        "option_selected": "Switch to Nhava Sheva backup terminal",
        "actual_outcome": "Backup terminal cleared backlog by day 3",
        "delivery_performance": "Recovered 1 day faster than predicted",
        "learning_signal": "Mumbai Port Strike pattern: prediction systematically over-states demand impact by ~3.5%",
        "severity_score": 8,
        "source": "Port Authority Alert",
        "timestamp_utc": "2025-02-28T09:15:00Z",
        "resolution_timestamp_utc": "2025-03-03T12:00:00Z",
    },
]

# ── Counterfactuals (R-05) ────────────────────────────────────────────────────
SEED_COUNTERFACTUALS = [
    {
        "counterfactual_id": "CF-SEED-001",
        "event_id": "EVT-SEED-001",
        "client_id": "demo",
        "actual_outcome": "Cyclone caused 5-day full disruption; air-freight bridge activated from Bengaluru",
        "prediction_variance": "Demand error +4.5%; risk scores within 7 points",
        "recalibration_recommended": True,
        "learning_signal": "Coastal-storm demand multiplier should be increased for Bay of Bengal events",
        "timestamp_utc": "2025-11-09T18:00:00Z",
    },
    {
        "counterfactual_id": "CF-SEED-002",
        "event_id": "EVT-SEED-002",
        "client_id": "demo",
        "actual_outcome": "14-day Shanghai freeze; Samsung SDI alternate activated in 72h",
        "prediction_variance": "Demand overestimated by 4.0%; alternate supplier faster than expected",
        "recalibration_recommended": False,
        "learning_signal": "Regulatory shutdown demand slightly over-predicted; alternate activation validated",
        "timestamp_utc": "2025-12-15T10:00:00Z",
    },
    {
        "counterfactual_id": "CF-SEED-003",
        "event_id": "EVT-SEED-003",
        "client_id": "demo",
        "actual_outcome": "Port strike resolved in 48h; Gujarat alternate covered shortfall",
        "prediction_variance": "Demand overestimated 1.5%; short-duration strike resolved ahead of forecast",
        "recalibration_recommended": False,
        "learning_signal": "Industrial action duration below worst-case; Gujarat corridor reliable",
        "timestamp_utc": "2026-01-12T16:00:00Z",
    },
]

# ── Seed events (HIL + simulation data for R-05) ─────────────────────────────
SEED_EVENTS = {
    "EVT-SEED-001": {
        "event_id": "EVT-SEED-001",
        "client_id": "demo",
        "monitor": {
            "severity_score": 8,
            "source": "IMD Cyclone Warning",
            "geography": "Chennai",
            "event_type": "Cyclone",
            "decision": "engage",
        },
        "simulation": {
            "simulations": [
                {"rank": 1, "label": "Air-freight from Bengaluru hub", "probability_valid": True,
                 "p10_cost_impact": 26.0, "p50_cost_impact": 34.0, "p90_cost_impact": 44.0},
                {"rank": 2, "label": "Emergency inventory release", "probability_valid": True,
                 "p10_cost_impact": 9.0, "p50_cost_impact": 15.0, "p90_cost_impact": 22.0},
                {"rank": 3, "label": "Re-route via Hyderabad supplier", "probability_valid": True,
                 "p10_cost_impact": 14.0, "p50_cost_impact": 20.0, "p90_cost_impact": 29.0},
            ],
            "duration_seconds": 22.4,
            "sla_breached": False,
            "sla_breach_requires_ack": False,
        },
        "hil_decision": {
            "selected_option_rank": 1,
            "reviewer_id": "demo_reviewer",
            "co_reviewer_id": "demo_co_reviewer",
            "co_review_required": True,
            "timestamp_utc": "2025-11-03T08:15:00Z",
        },
        "hil_acks": {"dissent": True},
        "timestamp_utc": "2025-11-03T06:00:00Z",
        "last_updated_utc": "2025-11-03T08:15:00Z",
    },
    "EVT-SEED-002": {
        "event_id": "EVT-SEED-002",
        "client_id": "demo",
        "monitor": {
            "severity_score": 8,
            "source": "Chinese Regulatory Monitor",
            "geography": "Shanghai",
            "event_type": "Regulatory Shutdown",
            "decision": "engage",
        },
        "simulation": {
            "simulations": [
                {"rank": 1, "label": "Switch to Samsung SDI Seoul", "probability_valid": True,
                 "p10_cost_impact": 18.0, "p50_cost_impact": 24.0, "p90_cost_impact": 32.0},
                {"rank": 2, "label": "Activate Pune buffer stock", "probability_valid": True,
                 "p10_cost_impact": 4.0, "p50_cost_impact": 8.0, "p90_cost_impact": 13.0},
                {"rank": 3, "label": "Air-freight from Taipei", "probability_valid": True,
                 "p10_cost_impact": 28.0, "p50_cost_impact": 36.0, "p90_cost_impact": 46.0},
            ],
            "duration_seconds": 19.7,
            "sla_breached": False,
            "sla_breach_requires_ack": False,
        },
        "hil_decision": {
            "selected_option_rank": 1,
            "reviewer_id": "demo_reviewer",
            "co_reviewer_id": None,
            "co_review_required": False,
            "timestamp_utc": "2025-12-01T10:00:00Z",
        },
        "hil_acks": {},
        "timestamp_utc": "2025-12-01T08:00:00Z",
        "last_updated_utc": "2025-12-01T10:00:00Z",
    },
    "EVT-SEED-003": {
        "event_id": "EVT-SEED-003",
        "client_id": "demo",
        "monitor": {
            "severity_score": 7,
            "source": "Port Authority Alert",
            "geography": "Mumbai",
            "event_type": "Industrial Action",
            "decision": "engage",
        },
        "simulation": {
            "simulations": [
                {"rank": 1, "label": "Activate Gujarat alternate supplier", "probability_valid": True,
                 "p10_cost_impact": 7.0, "p50_cost_impact": 11.0, "p90_cost_impact": 17.0},
                {"rank": 2, "label": "Expedite existing Pune orders", "probability_valid": True,
                 "p10_cost_impact": 3.0, "p50_cost_impact": 5.0, "p90_cost_impact": 9.0},
                {"rank": 3, "label": "Air-freight from Dubai", "probability_valid": True,
                 "p10_cost_impact": 20.0, "p50_cost_impact": 27.0, "p90_cost_impact": 36.0},
            ],
            "duration_seconds": 16.1,
            "sla_breached": False,
            "sla_breach_requires_ack": False,
        },
        "hil_decision": {
            "selected_option_rank": 1,
            "reviewer_id": "demo_reviewer",
            "co_reviewer_id": None,
            "co_review_required": False,
            "timestamp_utc": "2026-01-10T09:00:00Z",
        },
        "hil_acks": {},
        "timestamp_utc": "2026-01-10T07:00:00Z",
        "last_updated_utc": "2026-01-10T09:00:00Z",
    },
}
